apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-demo-app
  namespace: argocd
spec:
  project: default
  source:
    # REPLACE WITH YOUR GITHUB REPO URL
    repoURL: 'https://github.com/aws-devops-project/argo-rollout-blue-green.git'
    targetRevision: HEAD
    path: apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true