apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app-rollout
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    blueGreen:
      # Active service receives production traffic
      activeService: demo-app-active
      # Preview service receives upcoming version traffic
      previewService: demo-app-preview
      #Require manual promotion before switching active traffic
      autoPromotionEnabled: false
      # Scale down preview pods after promotion
      #scaleDownDelaySeconds: 30
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: webserver
        image: nginx:alpine
        command: ["/bin/sh"]
        args:
          - |
            echo '<!DOCTYPE html><html><body style="background-color:#1E88E5;color:white;text-align:center;padding-top:100px;font-family:sans-serif;"><h1>BLUE VERSION - Welcome to Node.js</h1></body></html>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
        ports:
        - containerPort: 80
          name: http