controller:
  kind: Deployment

  hostNetwork: true

  dnsPolicy: ClusterFirstWithHostNet

  service:
    type: ClusterIP

  ingressClassResource:
    enabled: true
    name: nginx
    default: true

  watchIngressWithoutClass: false

defaultBackend:
  enabled: false