apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: demo-rollout
  namespace: demo

spec:
  replicas: 2

  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: demo

  template:
    metadata:
      labels:
        app: demo

    spec:
      containers:

      - name: demo

        image: argoproj/rollouts-demo:blue

        ports:
        - containerPort: 80

        env:
        - name: PORT
          value: "80"

  strategy:

    blueGreen:

      activeService: demo-active

      previewService: demo-preview

      autoPromotionEnabled: false